### ISSUE TITLE
编译时出现的问题

### ISSUE THREAD

**Issue by NTY666233** [SakuraKoi/BridgingAnalyzer#1]
emmm我在近日试图使用IDEA编译插件但出现了问题 找他人求助也出现了同样的问题 以下是编译时的返回：
Information:java: Errors occurred while compiling module 'BridgingAnalyzer'
Information:javac 12 was used to compile java sources
Information:2020/1/10 17:42 - Build completed with 44 errors and 1 warning in 12 s 672 ms
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\api\BridgingAnalyzerAPI.java
    Error:Error:line (10)java: 找不到符号
  符号:   方法 setBlockSkinProvider(sakura.kooi.BridgingAnalyzer.api.BlockSkinProvider)
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (31)java: 找不到符号
  符号:   方法 setHighlightEnabled(boolean)
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (34)java: 找不到符号
  符号:   方法 setPvPEnabled(boolean)
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (37)java: 找不到符号
  符号:   方法 setSpeedCountEnabled(boolean)
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (40)java: 找不到符号
  符号:   方法 setStandBridgeMarkerEnabled(boolean)
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (44)java: 找不到符号
  符号:   方法 isHighlightEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (47)java: 找不到符号
  符号:   方法 isPvPEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (50)java: 找不到符号
  符号:   方法 isSpeedCountEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (53)java: 找不到符号
  符号:   方法 isStandBridgeMarkerEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\BridgingAnalyzer.java
    Error:Error:line (255)java: 找不到符号
  符号:   方法 setPvPEnabled(boolean)
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (269)java: 找不到符号
  符号:   方法 setPvPEnabled(boolean)
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (280)java: 找不到符号
  符号:   方法 isPvPEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (281)java: 找不到符号
  符号:   方法 isPvPEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (286)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (286)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Counter.java
    Error:Error:line (36)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (47)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (51)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (121)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (134)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (202)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (215)java: 找不到符号
  符号:   方法 getPlacedBlocks()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Cmmands\BridgeCommand.java
    Error:Error:line (35)java: 找不到符号
  符号:   方法 isHighlightEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
    Error:Error:line (36)java: 找不到符号
  符号:   方法 isHighlightEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
    Error:Error:line (40)java: 找不到符号
  符号:   方法 isPvPEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
    Error:Error:line (41)java: 找不到符号
  符号:   方法 isPvPEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
    Error:Error:line (45)java: 找不到符号
  符号:   方法 isSpeedCountEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
    Error:Error:line (46)java: 找不到符号
  符号:   方法 isSpeedCountEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
    Error:Error:line (50)java: 找不到符号
  符号:   方法 isStandBridgeMarkerEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
    Error:Error:line (51)java: 找不到符号
  符号:   方法 isStandBridgeMarkerEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 counter
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Cmmands\ClearCommand.java
    Error:Error:line (21)java: 找不到符号
  符号:   方法 getCounters()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Cmmands\SaveWorldCommand.java
    Error:Error:line (20)java: 找不到符号
  符号:   方法 getCounters()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\CounterListener.java
    Error:Error:line (36)java: 找不到符号
  符号:   方法 isSpeedCountEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 c
    Error:Error:line (46)java: 找不到符号
  符号:   方法 isSpeedCountEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 c
    Error:Error:line (66)java: 找不到符号
  符号:   方法 isSpeedCountEnabled()
  位置: 类型为sakura.kooi.BridgingAnalyzer.Counter的变量 c
    Error:Error:line (69)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (87)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\HighlightListener.java
    Error:Error:line (46)java: 找不到符号
  符号:   方法 isHighlightEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
    Error:Error:line (63)java: 找不到符号
  符号:   方法 isStandBridgeMarkerEnabled()
  位置: 类 sakura.kooi.BridgingAnalyzer.Counter
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\ResourcePackLoader.java
    Error:Error:line (13)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\TriggerBlockListener.java
    Error:Error:line (35)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
    Error:Error:line (117)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Utils\ParticleRing.java
    Error:Error:line (19)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Utils\TeleportRingEffect.java
    Error:Error:line (27)java: 找不到符号
  符号:   方法 getInstance()
  位置: 类 sakura.kooi.BridgingAnalyzer.BridgingAnalyzer
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Utils\ParticleEffects.java
    Warning:Warning:line (464)java: org.bukkit.Material中的getId()已过时
D:\桌面\BridgingAnalyzer\src\sakura\kooi\BridgingAnalyzer\Utils\Metrics.java
    Information:Information:java: /D:/桌面/BridgingAnalyzer/src/sakura/kooi/BridgingAnalyzer/Utils/Metrics.java使用了未经检查或不安全的操作。
    Information:Information:java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by SakuraKoi** [comment]
用了lombok
https://projectlombok.org/

**Comment by NTY666233** [comment]
导入lombok后出现的报错

**Comment by SakuraKoi** [comment]
你用的idea吧,安装idea的lombok插件并在设置中打开Annotations Processor

**Comment by LSDogX** [comment]
编译之前把项目编码转为UTF-8就可以了
