### ISSUE TITLE
release里的插件用不了

### ISSUE THREAD

**Issue by 1294966922** [SakuraKoi/BridgingAnalyzer#11]
release发布的插件扔进plugins启动后没反应

**Comment by SakuraKoi** [comment]
经测试(Spigot 1.8.8)工作正常

**Comment by SakuraKoi** [comment]
补充: 最低需要java8, 请确认java版本

**Comment by 1294966922** [comment]
用了java11直接启动不了下面是日志和启动脚本，求帮忙看看
[latest.log](https://github.com/SakuraKoi/BridgingAnalyzer/files/4972643/latest.log)
[启动服务器.txt](https://github.com/SakuraKoi/BridgingAnalyzer/files/4972658/default.txt)

**Comment by 1294966922** [comment]
用了java11,问题已解决，谢谢
