### ISSUE TITLE
不知如何设置返回出生点的坐标

### ISSUE THREAD

**Issue by SakuraTao2007** [SakuraKoi/BridgingAnalyzer#13]
你好作者！
BridgingAnalyzer不知如何才能设置返回出生点的坐标
一掉虚空（没踩绿宝石的情况下），或者踩青金石，都会卡虚空内
看了下源码，也没找到设置的地方（是我Java太菜了233）
求告知

**Comment by SakuraKoi** [comment]
默认出生点是世界出生点，各类修改出生点(如原版setworldspawn，ess的setspawn)均可生效

**Comment by SakuraTao2007** [comment]
> 默认出生点是世界出生点，各类修改出生点(如原版setworldspawn，ess的setspawn)理论上均可生效

好的，十分感谢
