### ISSUE TITLE
代码貌似有个错误的大写

### ISSUE THREAD

**Issue by LSDogX** [SakuraKoi/BridgingAnalyzer#15]
BridgingSkin.java 中第22行：
`import sakura.kooi.BridgingAnalyzer.Utils.Metrics;`
`.Utils.` 的 u 应该是小写的

**Comment by SakuraKoi** [comment]
NOTHING HAPPENED(雾

**Comment by SakuraKoi** [comment]
草,看错了,BridgingSkin.java里面啊(捂脸
好吧确实,这玩意好长时间没更新过了(
