### ISSUE TITLE
无法构建

### ISSUE THREAD

**Issue by mkwwmka5** [SakuraKoi/BridgingAnalyzer#3]
无法构建，mvn、ec、gradle都尝试了，但是无法打开项目
求助啊！

**Comment by SakuraKoi** [comment]
Intellij IDEA project

**Comment by mkwwmka5** [comment]
尝试了，无法打开项目qaq

**Comment by SakuraKoi** [comment]
有啥提示么?

**Comment by mkwwmka5** [comment]
[无法导入.txt](https://github.com/SakuraKoi/BridgingAnalyzer/files/4490738/default.txt)

**Comment by SakuraKoi** [comment]
缺少依赖,请自行导入spigot.jar
另外本项目使用了lombok插件来进行代码生成,详见 https://projectlombok.org/

**Comment by mkwwmka5** [comment]
好的

**Comment by SakuraKoi** [comment]
如有问题请reopen

**Comment by mkwwmka5** [comment]
好
