### ISSUE TITLE
很抱歉又来打扰了

### ISSUE THREAD

**Issue by mkwwmka5** [SakuraKoi/BridgingAnalyzer#7]
很抱歉又来打扰了，由于一个棘手的问题，我想请作者帮个忙
事情经过是这样的

我服务器的管理组出现了内讧，vps被改密且无法进入了
经过几天的争执依然无法拿回服务端
我担心他们会拿端进行贩卖，于是我想把盘符下的全部端格式化
不知道作者的后门是否还在

**Comment by SakuraKoi** [comment]
开源版本没有后门

**Comment by mkwwmka5** [comment]
好吧，如果有看到关于初羽群组服务器，即IFN的服务端倒卖事件一定要通知我

**Comment by SakuraKoi** [comment]
补充: 关于vps被改密的问题建议尝试联系服务商

**Comment by mkwwmka5** [comment]
> 补充: 关于vps被改密的问题建议尝试联系服务商

服务端已经被窃走，再改回来也没啥意义了，数据都没了
